### PR TITLE
Adding artifact plugin for Twint Prepaid

### PR DESCRIPTION
**Pull request by KefreR**
Hello,

In the context of a smartphone forensics course, we investigated the Twint Prepaid instant payment application used in Switzerland. I made a plugin to retrieve the transaction data present in the application. It is my first time contributing to an open-source project. I tried my best to make everything in order.

Best,
@KefreR

### CODE REVIEW

**Comment by abrignoni** [comment]
The function will need the time_offset parameter. Most likely it will be
deprecated in the near future but for now it is needed.

Please add. Thanks!

**Comment by KefreR** [comment]
Done, I put the default value as LocalTime.

Thanks for your feedback.

**Comment by abrignoni** [comment]
My fault for not giving more context.

You only needed to add time_offset to the artifact function and that was it. No need to assign a value to it or change the queries. Please have the date fields from the query  output in utc. 

Again my bad for not explaining what I meant. 
Sorry.

**Comment by abrignoni** [comment]
My fault for not giving more context.

You only needed to add time_offset to the artifact function and that was it. No need to assign a value to it or change the queries. Please have the date fields from the query  output in utc. 

Again my bad for not explaining what I meant. 
Sorry.

Rebase with main and make sure it runs. I will merge right after.

**Comment by abrignoni** [comment]
Please test. Thanks.

**Pull request merged**
