### PR TITLE
Add Ookla Speed Test App Parsing

### PR DESCRIPTION
**Pull request by mastenp**
Added support for the Ookla Speedtest Application including data related to each time an internet "speed test" was conducted.  Data includes Date/Time, External IP, Internal IP, Cellular Carrier (if test done over cellular connection),Device Model, ISP, WAN type, Wifi SSID (if test done over wifi connection), Lat/Long, Lat/Long Accuracy.  Sample of the report is below in the image. 

Screen Shot 2020-06-22 at 3 11 38 PM

### CODE REVIEW

**Comment by mastenp** [comment]
Just FYI 
-The Delete infoList.py is for another artifact that I didn't mean to bring in just yet, but Github Desktop grabbed it.
-The Delete ooklaSpeedtest.py was the script that I couldn't get working, so the working one is ooklaSpeetestData.py

**Comment by mastenp** [comment]
Added WAL file capability and updated the search for the database for Ookla Speed Test.

**Comment by ydkhatri** [comment]
Can you share a sample database (**speedtest.sqlite**) to test this with?

**Comment by ydkhatri** [comment]
Code looks good, but please remove the unused imports, like ccl_bplist, plistlib (and others) which aren't used.

**Comment by mastenp** [comment]
Removed unused Imports as requested.

**Pull request merged**
