### PR TITLE
Zangi Chats

### PR DESCRIPTION
**Pull request by dabeersboys**

### CODE REVIEW

**Review by dabeersboys — COMMENTED** [review]
reviewed, Zangi Chats artifact support

**Comment by stark4n6** [comment]
@dabeersboys do you want to keep the comments in?

**Comment by dabeersboys** [comment]
> @dabeersboys do you want to keep the comments in?
If its not too much trouble to remove them then they can be removed. OR I can go back, remove them and submit another pull request.

**Comment by stark4n6** [comment]
@dabeersboys I wasn't sure if you needed them for documentation or not, I can remove after the PR

**Pull request merged**
