### PR TITLE
New artifacts and fixed queries

### PR DESCRIPTION
**Pull request by any333**
Hi there!
I added a couple of artifacts and fixed some queries :)

### CODE REVIEW

**Comment by abrignoni** [comment]
This looks great! Will test and commit soon thereafter.

Thanks you so much. Looking at the code. Great work. 👏 👏 👏

**Comment by abrignoni** [comment]
Made some changes to the remiders.py script. It was generating an empty artifact report. Now it wont generate anything if there is nothing to show. Sadly my data sets have no databases with reminders to test. Please run the script on your data to confirm it works properly.

**Comment by abrignoni** [comment]
Also shorten the voice triggers files at section since the report has it per record. Used the main directory for the voice triggers instead. 

Thanks again for the artifacts. They are fantastic. Think you could add your information to the contributors list in the version_info.py script @any333?

**Comment by any333** [comment]
I'm happy to help! 
There was a small issue in reminders.py, you can find the fix for it in the next pull request. The if and the for statement on line 25 respectively 27 were not correctly indented and thus every extracted entry was stored as many times as the number of files found.

**Comment by abrignoni** [comment]
Awesome! Thanks!
👏 👏 👏 👏

**Pull request merged**
