### PR TITLE
remove os.getcwd() in location determination code

### PR DESCRIPTION
**Pull request by ydkhatri**
Please test with the exe version.

### CODE REVIEW

**Comment by abrignoni** [comment]
Downloaded the fork and created the binaries.

The cmd line version produced errors in the format of “Could not write file
to file system, path was “ for the snapshot artifact. The report showed
only 18 snapshots instead of the expected 290 + snapshots.

The GUI version showed 297 snapshots and no errors in the log.

The notifications looked fine on both. I used Hickman’s image.

**Comment by ydkhatri** [comment]
> The cmd line version produced errors in the format of “Could not write file to file system, path was “ for the snapshot artifact. The report showed only 18 snapshots instead of the expected 290 + snapshots.

Hmm, then that is probably not related to this change, but I will take a look at the cmd version and get back to you on it.

**Comment by ydkhatri** [comment]
This had to do with long file paths, now fixed..

**Comment by abrignoni** [comment]
Release has been updated.
Windows 10 64-bit.

**Pull request merged**
