### PR TITLE
Updates to parsed embedded files plists and jpgs 

### PR DESCRIPTION
**Pull request by ScottKjr3347**
updates to photos.sqlite parsers for embedded plists and embedded preview jpgs.

### CODE REVIEW

**Comment by abrignoni** [comment]
I agree. Think you could make the exclusion? If not I will look at the code and try to find where it is done now after the GUI changes. 🙂👍

**Comment by Johann-PLW** [comment]
Sure.
I know the code a lot better now 🤪 and know exactly where it is done.
I'm also going to check all the modules.

**Comment by ScottKjr3347** [comment]
Thanks for looking at these ph94-97 should be excluded by default. I just haven't found the file to change the included/exclude them by default yet.

**Comment by Johann-PLW** [comment]
Thank you very much @ScottKjr3347 
I am allso going to exclude by default Ph94-97.
The modules to exclude by default are indicated in ileapp.py and ileappGUI.py scripts. But I like the idea to create a separate file to do that. I will see what I can do

**Pull request merged**
